name: build-tes-report
author: mchaouachi
description: build-test-report
inputs:
  working-directory:
    required: false
    default: ''
    description: Working directory
  skip-test:
    required: false
    default: 'false'
    description: Working directory


runs:
  using: "composite"
  steps:

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'maven'
    - name: Run Checkstyle Analysis
      run: mvn checkstyle:checkstyle
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - name: Run Checkstyle Analysis
      if: ${{ inputs.skip-test != 'false'}}
      run: mvn test
      shell: bash
      working-directory: ${{ inputs.working-directory }}


