name: Build and Test Java Application on Push
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run:  cd java-app && mvn clean install

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: ./java-app/target/*.jar