on [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Greetings, run a one line script
              run:
                  echo "Hello, World!"build