name: Use my Action
on:
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Test Composite Action
        uses: ./.github/actions/build-test-report
        with:
          working-directory: './java-app'
          skip-test: false


